### ISSUE TITLE
get photos from club activity

### ISSUE THREAD

**Issue by mauradaffern** [stravalib/stravalib#103]
Hello,

I am attempting to iterate through the activities I have obtained from a club.  How can I get the photo associated with an activity?  I'm having problems figuring it out. 

Thank you!

**Comment by lwasser** [comment]
hi there @mauradaffern this issue is 6 years + old now! and we've totally redone the stravalib API. 
[there is another related issue here](https://github.com/stravalib/stravalib/issues/232). so for the time being i'm going to close this. i think strava only supports [a few endpoint options](https://developers.strava.com/docs/reference/#api-models-PhotosSummary) officially and then there may be some undocumented support. but for now let's close this. Please feel free to create a new issue if you are still having issues with the new API work we've done (and knowing only some of the photo features in strava are actually supported in their current api!
