### ISSUE TITLE
get_activity issues errors

### ISSUE THREAD

**Issue by gringorichards** [stravalib/stravalib#159]
No such attribute visibility on entity <Activity id=X name='Morning Ride' resource_state=3>
No such attribute available_zones on entity <Activity id=X name='Morning Ride' resource_state=3>

Get_activities does it too.

Sorry if it's something I am doing wrong but couldn't work out how to stop it popping up!

Thanks

**Comment by ashleyshine** [comment]
Came here for the same reason; looks like somewhere along the line the warnings are being logged because the `get_activities()` call tries to retrieve a visibility attribute from the Activity entities.

In the meantime, a quick fix to make the warnings go away is to set the logging level higher than WARNING: 
```
Log = logging.getLogger()
Log.setLevel('ERROR')
```

**Comment by gringorichards** [comment]
Thanks, was trying everything under the sun to suppress the list of warnings in my Jupyter Notebook - your quick fix did the trick!
Glad to see I wasn't imagining it too.

**Comment by hozn** [comment]
Thanks for the heads up -- I'll push out a fix to correct the expectation
of these attributes being present.

**Comment by gringorichards** [comment]
Thank you very much. It's a great library.

**Comment by jsamoocha** [comment]
Fixed by #350
