### ISSUE TITLE
Athlete support in webhook

### ISSUE THREAD

**Issue by f1gjam** [stravalib/stravalib#208]
Add support for athlete in webhook.

This will allow to delete athlete etc...

**Comment by lwasser** [comment]
hey @f1gjam i'm checking in on old issues!! this one is a few years old and since we've updated our API significantly. 

We do currently have `get_athlete` and `update_athlete` as methods available to use in our API.  Please let us know if you've tried those and are encountering issues or not! Because this issue has been open for so long, i'll close it in a week if we haven't heard back from you. But if you have tested against the new api and are still having issues let's discuss the issues here!

**Comment by f1gjam** [comment]
Hi,

the issue was to do with orphaned athletes. 

I had an issue where I wasn’t cleaning up athletes properly and so I had athletes whose activities were still being sent to my app. This was because the app was not deleted from their Strava apps.

I didn’t have a token for the user anymore and so I couldn’t stop this.

what would be useful is to allow the app owners to remove athletes from their apps.

this could be because of a mistake in cleanup as was in my case.

or you as the owner of the app you want to remove the user and have lost the token etc…. 

Either way it doesn’t cause any harm to athletes etc…

**Comment by lwasser** [comment]
hey @f1gjam thank you for the explanation. This issue sounds like something on the strava  app setup end of things rather than our python implementation that interacts with the API and returns data. 

I don't think we as maintainers of the stravalib library can help you with managing users interacting with your app.

i am going to close this . However, if there is something that I am missing, please reopen. you could also potentially post in our discussion forum to see if other devs have a work around for such issues.
