### ISSUE TITLE
API out of date

### ISSUE THREAD

**Issue by johnkendall** [stravalib/stravalib#212]
There seem to be numerous faults with the stavalib library due to changes in the Strava API. Just a few:

.get_athlete(id) The /athletes/{id} endpoint was removed by Strava.  See https://developers.strava.com/docs/january-2018-update/
.get_athlete_friends() Returns error 403 Client Error: Forbidden [Forbidden[]].
.get_athlete_followers() Returns error 403 Client Error: Forbidden [Forbidden[]].
kudos - attribute premium deprecated - changed to summit

**Comment by lwasser** [comment]
hey @johnkendall this issue is a few years old now and we've totally updated the stravalib API! i am going to close this issue as i suspect all of the above has been fixed (or there could be different unknown to us yet issues)! However, if you are still having issues with the API endpoints failing please reopen and we can discuss it further here. i'm just trying to cleanup some of our older issues that might have been addressed.
