### ISSUE TITLE
Photos Endpoint Does Not Exist

### ISSUE THREAD

**Issue by samryan18** [stravalib/stravalib#232]
As far as I can tell, this method should not exist or should at least raise something like a `NotImplementedError`:
https://github.com/hozn/stravalib/blob/b8d1181e32248c6570f0adfa995cb6c7adfccf62/stravalib/client.py#L809

This endpoint does not appear to exist in the [Strava API](https://developers.strava.com/docs/reference/#api-Activities):
https://github.com/hozn/stravalib/blob/b8d1181e32248c6570f0adfa995cb6c7adfccf62/stravalib/client.py#L837

It appears that these are the only two photos models Strava supports (suggesting that it is only possible to retrieve urls for primary photos):

<img src="https://user-images.githubusercontent.com/23075262/147145991-3c51a16b-85e0-4bfa-8f2e-2d6643528f2a.png" height="400px">

**Comment by samryan18** [comment]
If I am wrong (I hope I am!), please do let me know / correct me. Wish Strava supported this..

**Comment by samryan18** [comment]
Looks like this is a duplicate/subset of #230 

Will leave it open in case someone has suggestions for this particular issue.

**Comment by lwasser** [comment]
@samryan18 i think it's great for us to identify broken API endpoints and deprecate them in the code.  maybe having a milestone related to broken endpoints that we can chip away at would be helpful here as there are a bunch of them! Are you comfortable submitting a PR to remove these end points or target the endpoints that work? no worries if you are not! i know right now the test suite is a bit tricky to run.

**Comment by lwasser** [comment]
hey @samryan18 i'm going through and cleaning up old issues. we (@jsamoocha ) :)  redid the stravalib API and are created our models from the actual strava swagger.json api.

you are correct in that this endpoint is not officially documented. [We do have some support for it](https://github.com/stravalib/stravalib/issues/443#issuecomment-1762893247) however, as you pointed out, it could fail at any time because Strava doesn't officially support it! 

i am going to close this issue now, however, please do feel free to reopen it (or create a new issue!) if there are things we can help with associated with our new refactored api!
