### ISSUE TITLE
Discussion: Consider Pydantic as a replacement for homegrown Models / Attributes framework ?

### ISSUE THREAD

**Issue by hozn** [stravalib/stravalib#248]
A key value-add, in my opinion, for Stravalib is the modeling of the entities from Strava in a way that makes them easy for API users to integrate with their applications.  Not just the stronger typing that is increasingly helpful in larger Python applications, but also handling speed/distance units and conversions.   Since this library has been written, we've had some great new packages added to the python ecosystem.  We've also had newer python introduce native dataclasses.  For awhile [Marshmallow](https://marshmallow.readthedocs.io/en/stable/) was something I'd been looking at to change how we were modeling the Strava entities; however, I think the clear front-runner in recent years is [Pydantic](https://pydantic-docs.helpmanual.io/). 

I think the main benefit to this would be embracing what is becoming (or feels like it is becoming) the standard for modeling (de)serializable data classes in python.  Pydantic is easily customized to handle more complex deserialization (or serialization) of these dataclass models.

More thought would need to be given to how to handle units & type conversions, the current way of expressing the different detail levels and which attributes are present, etc.  (The latter may not be strictly necessary either?)

I haven't fully thought this through or proven it out; this is more just an observation that stravalib rolls its own (de)serialization & modeling framework, which may be better handled by purpose built tooling in 2022.  So just wanted to propose this idea for consideration if there is a plan to do a major version bump & break backwards compatibility.  (This would also mean supporting only newer Python 3, but I think that is probably acceptable with a major version bump.)

**Comment by lwasser** [comment]
@hozn i always think that if there is a really well maintained tool that implements functionality that we'd be maintaining manually here, it's worth considering adding it as a dependency and refactoring code. It seems like we're already moving away from python 2.x and i think we are at >=3.7 at this point given the CI changes implemented already! 

So i suppose the question is, how much work would this entail? We also should probably get all of our infrastructure, tests, etc updated first as well :)

**Comment by jsamoocha** [comment]
I did a first (very premature) POC with pydantic. It was quite an effort to generate the model from Strava's published API definition because they use swagger 2.0, while Pydantic's code generation tools expect OpenAPI3. With the help of a [swagger -> OpenAPI3 conversion API](https://converter.swagger.io/api/convert) and some recursive generation of schemas from `$ref`s, it was possible to create a valid OpenAPI3 YAML file that could be processed by Pydantic's [code generation tool](https://github.com/koxudaxi/datamodel-code-generator/). I haven't tried it yet, but the code generator even promises to be able to generate docstrings for the domain classes.

Next, I was able to retrieve an activity from Strava and deserialize it to a model class:

<img width="584" alt="stravalib_fork_–_strava_api_yml" src="https://user-images.githubusercontent.com/1788027/205678684-e4a9aee3-e5ca-4aa1-9302-8e4b5b0ba924.png">

It became immediately clear that Strava sends more attributes in the response than what they officially mention in the published API (there were 19 attributes in the response that were missing in the `DetailedActivity` model).

Using the above approach will allow us to do the following automatically, e.g., daily using a GitHub Action:

- create a branch
- generate the model from Strava's swagger file
- git diff with the model on the main branch
- if there's a diff, create a PR (which will trigger CI and let us know if there are issues with the Strava changes)
- we only need to merge these PRs to deal with Strava changes on the domain model

### Some stuff to consider:

#### Backward Compatibility

We may need to customize/subclass the generated models to retain the same names and behavior of our existing model classes (e.g. to use the bound client for lazy retrieval of nested objects).

#### Strava Reliability

The above approach will work only if Strava has the discipline to update their API swagger. I have no idea if and how often that happens. I'll start to manually check this for the next weeks/months before diving into this further.


Please let me know what y'all think about this approach!

**Comment by lwasser** [comment]
woah. @jsamoocha what were the addition attributes ?

This would be an amazing approach. 
For kicks, i did a bit of digging. 
they (strava) aren't the best at versioning and feature tracking BUT strava changelog had two elements that were deprecated in October 2022
`Deprecate page and per_page params`

https://developers.strava.com/docs/changelog/ 

and if you look at the swagger.json those changes are indeed there

```
        {
            "name": "page",
            "in": "query",
            "description": "Deprecated. Prefer to use after_cursor.",
            "type": "integer"
          },
          {
            "name": "per_page",
            "in": "query",
            "description": "Deprecated. Prefer to use page_size.",
            "type": "integer",
            "default": 30
          },
          {
            "name": "page_size",
            "in": "query",
            "description": "Number of items per page. Defaults to 30.",
            "type": "integer",
            "default": 30
          },
```

So this could be a brilliant approach to ensuring we are a bit m ore in sync with strava changes. and we should just assume that at times endpoint functionality won't be documented as it has been consistently that way. 

## What i don't understand - backwards compatibility implementation 
The only point that i don't understand the implementation of above is the backwards compatibility section.  i don't fully understand how we'd implement that piece. can you please help me understand what that would look like?

AND

what happens if the reliability that we think / hope is there isn't there? how would we then (manually?) update parts of the model as they change?

**Comment by jsamoocha** [comment]
These are the "unofficial" attributes: 
```
{'available_zones',
 'average_cadence',
 'average_heartrate',
 'display_hide_heartrate_option',
 'from_accepted_tag',
 'has_heartrate',
 'heartrate_opt_out',
 'location_city',
 'location_country',
 'location_state',
 'max_heartrate',
 'perceived_exertion',
 'pr_count',
 'prefer_perceived_exertion',
 'resource_state',
 'similar_activities',
 'stats_visibility',
 'utc_offset',
 'visibility'}
```

For reference, I'm attaching the generated (by me) OpenAPI YAML file and the generated (by [datamodel-code-generator](https://github.com/koxudaxi/datamodel-code-generator/)) alt_model.py module. The datamodel code generator has many options that I haven't tried yet.

[model_files.zip](https://github.com/stravalib/stravalib/files/10163687/model_files.zip)

About backward compatibility:

As an example, we currently have an `Activity` class. The generated code (based on Strava's definition) calls this class `DetailedActivity`. We can at least retain the same type name (and some of its associated behavior as seen in the `zones` or `kudos` properties) by making `Activity` a subclass of the generated `DetailedActivity` and implementing this bound client behavior in the subclass. We could even (manually) add the "unofficial" attributes from above to that subclass.

Of course, the _exact_ type of `Activity` will be different (as it is now a subclass of Pydantic's `BaseModel`), so any user code that does `isinstance()` checks on `stravalib` model objects will be broken. Since this change will also completely remove the `attributes` module, any user code referencing that* will be broken. So 100% backward compatibility is not feasible, I'm afraid. But by subclassing the generated model classes, we should be able to retain most of today's functionality and API.

I hope this (+ the example files) explains it a bit more!

(*) I have no idea why anyone would do that, but it's (theoretically) possible.

**Comment by hozn** [comment]
Wow, amazing work @jsamoocha !  I obviously have been mostly otherwise occupied, but impressed that you were able to get up and running with the code generation; I'll admit that I haven't used that at all.  I have used pydantic with tools like FastAPI to create JSON schema and interactive opanapi docs, which is a pretty neat feature / benefit of the pydantic modeling.

**Comment by lwasser** [comment]
woo hoo! So... i guess my question here is how do we decide to move to this type of approach to generating our classes? it seems like a relative large overhaul of the package structure? I love the idea in concept. but would want to test the implementation before disrupting users and also am still a bit nervous about what backwards compatibility looks like. 
And second @hozn comment above!!

Such incredible work @jsamoocha you have improved the package so much already!! Go maintainer team!! 🚀

**Comment by jsamoocha** [comment]
I tried out several bits and pieces to better understand what needs to change. I propose gradually adding updates in separate PRs instead of one massive amount of work to make reviewing easier. I added a branch, `pydantic_model`, and intend to merge all these PRs into that. If that branch is finished and stable, we can merge everything at once into `master` (which will keep `master` stable during the development of the pydantic model).

I'm thinking about the following pieces of work:

- [ ] GitHub action that generates the pydantic model from Strava's swagger API definition
- [ ] Workflow that uses the above action and creates a PR in case of changes
- [ ] Rewrite of the existing `model` module, with existing model classes replaced by subclasses of the pydantic model. Removal of the `attributes` module.

And for backward compatibility:

- [ ] Making our new-style model classes return `Quantity` objects where the current ones do
- [ ] Rewrite of `BatchedResultsIterator` to use pydantic's deserialization
- [ ] Extending the new-style model classes to allow using a bound client
- [ ] Extending the new-style model classes to allow some undocumented attributes (that are supported by the existing model)

Please let me know if the above approach works for you all, or if I missed something regarding backward compatibility.

**Comment by jsamoocha** [comment]
To keep things clean(*) within this package, I created [another repo](https://github.com/stravalib/strava_swagger2pydantic) within the stravalib organization for the GitHub Action that generates the model. Since I transferred this from my account, there's no PR for most of the added code. But please review the single python file and action.yml if possible.

(*) It has code and dependencies that are irrelevant to this package.

**Comment by lwasser** [comment]
Sorry I've been so quiet. Will try to catch up and respond soon!!

**Comment by jsamoocha** [comment]
For the first time, the bot picked up an (undocumented) change in the Strava API in my test repo 😁:

<img width="662" alt="_CHANGE__Strava_API_Change_by_github-actions_·_Pull_Request__8_·_jsamoocha_strava_change_pr_test" src="https://user-images.githubusercontent.com/1788027/213635843-ed62421f-37c7-463e-bd34-c3f30c5cfaa6.png">

**Comment by yihong0618** [comment]
> For the first time, the bot picked up an (undocumented) change in the Strava API in my test repo 😁:
> 
> <img alt="_CHANGE__Strava_API_Change_by_github-actions_·_Pull_Request__8_·_jsamoocha_strava_change_pr_test" width="662" src="https://user-images.githubusercontent.com/1788027/213635843-ed62421f-37c7-463e-bd34-c3f30c5cfaa6.png">

cool

**Comment by lwasser** [comment]
Wow!!! What a cool message to wake up to! That is soooo awesome jonatan!!

what a good idea you had w this big change to how the model is created!!!
Yay!
