### ISSUE TITLE
Units dependency seems to be abandoned

### ISSUE THREAD

**Issue by jsamoocha** [stravalib/stravalib#281]
The `units` package seems not to be maintained any longer (the latest release on PyPi is from 2017, and its source repo has vanished).

In line with #248, we need to start thinking about an alternative, possibly from [this list](https://socialcompare.com/en/comparison/python-units-quantities-packages).

**Comment by lwasser** [comment]
We should definitely move away! how does this relate to using pydantic? i know that the scipy ecosystem has significant support right now through the scientific python effort so my vote is using constants onlyl because i know it's really readily used, not because i've used it myself before. 

I'm also not familiar with pydantic!

**Comment by jsamoocha** [comment]
I referred to #248 because it isn't clear to me right now how/if deeply interwoven `units` is within the existing framework of `model` and `attributes`. Pydantic itself does not seem to have unit conversion such as feet -> meters, so maybe Pint is a good lightweight alternative.
