### ISSUE TITLE
Bump to 1.1 to test deployment and release all of the changes we've made in the past month (which is a lot!)

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#295]
Heya @jsamoocha no rush on this but i just wanted to ensure that your comment about testing deployment didn't get lost! whenever you feel like testing a new release i'm game!! but there is of course no rush at all here.

**Comment by jsamoocha** [comment]
I tried to follow the guidelines in the documentation but got stuck at the very first step of testing the installation from test pypi:

```
Python 3.10.8 (main, Dec  4 2022, 13:57:44) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from stravalib import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jsamoocha/.local/share/virtualenvs/stravalib-test-N6jISpEp/lib/python3.10/site-packages/stravalib/__init__.py", line 1, in <module>
    from stravalib.client import Client
  File "/Users/jsamoocha/.local/share/virtualenvs/stravalib-test-N6jISpEp/lib/python3.10/site-packages/stravalib/client.py", line 18, in <module>
    from units.quantity import Quantity
ModuleNotFoundError: No module named 'units.quantity'
```

Whenever my python version is lower than 3.10, the above import works fine.

Also, whenever I locally build the wheel from the master branch and install it in a different target venv (regardless the python version of either build or target venv), the above import works fine.

I'm a bit puzzled. If you haven't done so already, could you please test at your end if you can install the current wheel from test pypi into a py3.10 environment?

**Comment by lwasser** [comment]
Oh weird. Sure I'll check that out today either during lunch or after work.

**Comment by jsamoocha** [comment]
It looks to be a pipenv issue. Pipenv seems to (based on its version) install different versions of `units`. Something in its dependency resolution seems to be broken since it installs versions of `units` that (according to pypi) don't exist (e.g., 0.7 or 1.0, while pypi mentions 0.07 as the latest release). Trying to figure out now why the locally built wheels do install correctly...

**Comment by lwasser** [comment]
oh that's interesting. i was going to ask to see your environment if it worked for me. i haven't tested it yet. i'm a bit worried given units last commit was 2017. maybe we prioritize moving away from it in the next weeks? 

When you install with pip install -e do the dependencies for stravalib install correctly? 

There are two places where depdencies could install.

When you pip install requirements.txt units is there (and we don't have a version pinned)
When you pip install stravalib the requirement should also install. (or from wheel)

it's worth looking into where the failure is occurring.
We could also look into dependency pinning.

Honestly @jsamoocha this might be a good reason to use poetry as it will manage this for us. that's it's strength .  are you open to that?

**Comment by lwasser** [comment]
when you start to pin deps it's really important to get the resolution of all deps correct.

**Comment by jsamoocha** [comment]
It's totally fine with me to use poetry (or pipenv as a sometimes quirky alternative) for our own dependency management.

Given that `units` is so old and not maintained any longer, this issue may take a lot of time to resolve. When I look in `site-packages`, whatever is installed as `units` 0.7 is completely different from 1.0 (which both don't exist in pypi 🙈).

When looking at our existing code, I think I can easily rewrite `unithelper` to use `pint` instead of `units` while maintaining the same interface. The other uses of `units` are some type checks of the `Quantity` type (which is also there in `pint` BTW). So maybe let's try this instead of trying to resolve this pinning/versioning issue?

**Comment by jsamoocha** [comment]
I just checked one more time to make sure nothing malicious was happening. So it turns out the latest pipenv somehow finds and installs a totally different `units` from [this repo](https://github.com/ndeutschmann/py-units). It has the same package name but is not listed on pypi.

Will take a look into having a fix for #281

**Comment by lwasser** [comment]
that hurts my brain 😆 . i am confused. is `pipenv` using pip to resolve dependencies? regardless dropping units seems like the path forward . so glad that you caught this and glad we have test pypi to catch these things. 

but also a bit concerned CI didn't catch it. i have asked some friends about why this might have happened and also will think about ways we could make sure CI catches it in the future!!

**Comment by lwasser** [comment]
so i think we can close this. successful release! @jsamoocha  if you  noted any issues with any of the infrastructure or docs let me know and I can fix. but it seems like this release went smoothly other than the python dependency glitch which we knew was an issue. closing this but reopen if you feel like we need to modify anything in our release workflow.
