### ISSUE TITLE
can I access or set the sub type of an activity?

### ISSUE THREAD

**Issue by think-nice-things** [stravalib/stravalib#360]
Hi,

in strava I can set sub types like Mountain Bike (MTB) as sub type of Bike for activities.

In stravalib, activities seem to have type == 'Ride' for example but I didn't find the possibility to access or set sub types like MTB.

Is this missing or did I just not find it?

**Comment by lwasser** [comment]
hey there @think-nice-things ! welcome to stravalib!

Great question!! 
i only have runs and hikes in my list of activities BUT i think you want the `sport_type` key rather than `type` to get at the "sub type" 

If i authenticate and collect activities:

```
activities = client.get_activities(after="2023-03-01")
```
Then i loop through my activities - notice if i call the sport_type key i get a "trail run" which is a sub type of "run"

```python
for activity in activities:
        my_dict = activity.to_dict()
        print(my_dict["sport_type"])
        print(my_dict["type"])
```

returns (where hike is just a hike always) but trailRun is actually a subtype (sport type) of run (a type).
```
'TrailRun'
'Run'
'Hike'
'Hike'
```
[You can see more about the various API endpoint return info here.](https://developers.strava.com/docs/reference/#api-Activities-createActivity)

hopefully that helps!

**Comment by think-nice-things** [comment]
Hi,

I modified stravalib to support 

```python
client.update_activitiy(sport_type='...')`
```

From [the strava api UpdatableActivity](https://developers.strava.com/docs/reference/#api-models-UpdatableActivity) it seems to me that `type` is deprecated anyway in favour of `sport_type`.

Anyone who should send the patch to? (I probably don't have write access to the git).

**Comment by jsamoocha** [comment]
Hi,

Thanks for working on the `update_activity()` method! You can [create a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) to incorporate your changes into this repository. The docs have a more detailed [contributing guide](https://stravalib.readthedocs.io/en/latest/contributing/how-to-contribute.html).

Please don't hesitate to reach out if you have more questions or need help with the above.

**Comment by lwasser** [comment]
also just a note that you can install version 1.3 as a release candidate via pip `pip install stravalib==1.3.0rc0` but i did open an issue to bump to 1.3 given that RC has been out for 2 months without any issues here!

**Comment by jsamoocha** [comment]
Let's add the fix for this deprecation of the (activity_)`type` param and its replacement by `sport_type` to the coming 1.3 release (since `sport_type` was also introduced into this codebase by the Strava-generated pydantic model).

**Comment by lwasser** [comment]
Sounds good!
