### ISSUE TITLE
Typing issue with the strava API bot

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#479]
Although the strava API change PR bot runs again, it seems to generate code that conflicts with some editing we did (see some of the typos in comments that originate from Strava.

Also, the generated container types are not the "plain" python `list,` but rather `typing.List`, which is odd since we set 3.9 as the python version for the generator. Will need to look into that later (that's in the strava_swagger2pydantic repo).

_Originally posted by @jsamoocha in https://github.com/stravalib/stravalib/issues/477#issuecomment-2041018918_

**Comment by lwasser** [comment]
i created this issue @jsamoocha @enadeau @yihong0618 to capture what Jonatan observed in these prs! you can see the implementation of this in #480  opened by the bot workflow

**Comment by jsamoocha** [comment]
I now see why we don't get the "modern" typing out of the strava_swagger2pydantic action. When it runs

```ruff check $MODEL_FILE --fix --unsafe-fixes```

ruff uses the configuration from `pyproject.toml` in the _stravalib_ repo (instead of the config from the strava_swagger2pydantic repo). It needs the latter, because of the extra check for UP rules (pyupgrade). If any of y'all knows a quick fix for this it would be great. Otherwise, I'll need to research it.

**Comment by enadeau** [comment]
It's probably simpler to stop using ruff for this purpose and rather rely on the datamodel-code-generator option that was mentionned here https://github.com/koxudaxi/datamodel-code-generator/issues/1523

The ruff thing was mostly a temp fix on my part when I did that because didn't know how to do better.

I'll try to make the change

**Comment by enadeau** [comment]
Here it is https://github.com/stravalib/strava_swagger2pydantic/pull/10

@jsamoocha  just needs review but I don't have right to request review on that repos

**Comment by jsamoocha** [comment]
Thanks! Because of the ruff addition, I assumed this was impossible with the datamodel-code-generator. Everything is running as expected now!
