### ISSUE TITLE
Stravalib 2.0 -> Documentation Update

### ISSUE THREAD

**Issue by jsamoocha** [stravalib/stravalib#502]
- [x] Incorporate all (breaking) changes in the documentation
- [x] Filter base type members from new custom types (e.g., `Duration` will, by default, include members of `int`)
- [x] Add examples of using the new custom types in docstrings
- [x] Add examples of using the new custom types in a new documentation section (about unit conversion)

**Comment by lwasser** [comment]
i am happy to help with the docs. i could even start a page now pulling from the hackmd file that has notes in it. Just let me know how i can be helpful in all of this!

**Comment by jsamoocha** [comment]
Thanks! Let's wait with this until some of the other issues are resolved and we have a definite understanding of how our API will look like.

**Comment by lwasser** [comment]
sounds great!

**Comment by lwasser** [comment]
i'm actually revisiting this original issue you opened in May that has the things i want to work on. Do you think we should chip away at the other items first before i dig too much into the docs? am I jumping the gun? i may be able to to do a bit more work this weekend on something .

**Comment by jsamoocha** [comment]
Only a tiny bit of work is left in #501, which does not affect documentation or user-facing API. If you want me to help with specific sections of the documentation or examples, please let me know.

**Comment by lwasser** [comment]
@jsamoocha that would be great. Id LOVE help with 

1. the section on deprecations/ breaking changes in stravalib 2.x. I was thinking i could add a banner to the top of the docs that linked to that page to alert users of the changes! Similar to what pydantic did. it's a built in feature of our theme to do this. 
2. with examples. 

Suggestion: How about i take my current pr  with the inheritance diagrams. (i can do this tonight). i'll split the pr into two:

1. clean the docs / add autoapi as our main autodoc tool + a banner at the top for the stravalib 2.x page.  i can create an empty deprecation page with some notes from our hackmd file. we can quickly merge this pr as it's just a structural update 
2. the inheritance diagrams + filtering of methods from objects like `int`

You can then work on the deprecated items page in a separate pr. and examples as you see fit!
 
i'll work on the inheritance diagrams and customizing new autoapi module which i've been playing with to filter things. Based on my research this extension should do what we want it to BUT I haven't tried that yet to do that specifically! I really like the extension because we literally do nothin to add things to the api docs. 

[demo of the docs here](https://github.com/pyOpenSci/pyosPackage)
[package structure here](https://github.com/pyOpenSci/pyosPackage)

it just creates the api docs on build and adds them to our docs!! 
Does that seem reasonable? i can also likely help more with examples later.

**Comment by lwasser** [comment]
ok what's left here

✅ Incorporate all (breaking) changes in the documentation #537 just merged addressed this with @jsamoocha new migration page. 
✅  Filter base type members from new custom types (e.g., Duration will, by default, include members of int) also  implemented in #537 [here](https://github.com/stravalib/stravalib/pull/537/files#diff-85933aa74a2d66c3e4dcdf7a9ad8397f5a7971080d34ef1108296a7c6b69e7e3R161)
✅  Add examples of using the new custom types in docstrings
- [ ] Add examples of using the new custom types in a new documentation section (about unit conversion) -- this is [referenced here](https://github.com/stravalib/stravalib/pull/537/files#diff-c00f99c359fd5cf83055e48da4ec9e6aadd43b0123b25aca1e63bf43e691787dR40) 

we could add it to the main documentation as well but that also could be a future pr where we have more "how to" content. 

@jsamoocha what do you think? 

note: i do have time to work on things now that i'm back from travel. but it would also be nice to cut a (pre) // release candidate for testing on pypi sometime soonish if most of the core work is done!!

**Comment by jsamoocha** [comment]
I'll add a mini-tutorial in the same fashion as we did for athletes, activities, etc. in a new PR

**Comment by lwasser** [comment]
This is complete! closing
