### ISSUE TITLE
BUG: Pydantic version upgrade to >2.0

### ISSUE THREAD

**Issue by claytonneal** [stravalib/stravalib#523]
### Stravalib version checks

- [X] I have tested this in a new clean environment with only stravalib and core python files.

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/stravalib/) of stravalib.

- [ ] I have confirmed this bug exists on the [main branch](https://github.com/stravalib/stravalib) of stravalib.

### What operating system are you seeing the problem on?

Mac

### What version of python or you running?

```python
3.12
```

### Reproducible Example

```python
N/A
```

### Issue Description

stravalib depends on pydantic < 2.0 - therefore cannot be used inside same project that us using >2.0
please consider upgrading

### Expected Behavior

support pydantic >2.0

### Your environment

<details>

Because stravalib (1.7) depends on pydantic (<2.0)
 and no versions of stravalib match >1.7,<2.0, stravalib (>=1.7,<2.0) requires pydantic (<2.0).
So, because <myproject> depends on both stravalib (^1.7) and pydantic (^2.7.4), version solving failed.

</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lwasser** [comment]
hey @claytonneal 👋🏻 Thanks for submitting this issue! 

We are actively working on migrating to pydantic v2 + a major cleanup of the API now - [on this branch here.](https://github.com/stravalib/stravalib/tree/pydantic-v2). It will take some time however for us to complete everything. If there are other items that you wanted to discuss we can leave this open, but otherwise please know that this is in progress actively now!

**Comment by lwasser** [comment]
Clayton, i'm going to go ahead and close this - but feel free to keep tabs on things in our pydantic-v2 branch where we are doing the migration work / updating / fixing a lot of things in our api!! thank you again for opening this issue. Please reopen if you feel as if there is something i haven't addressed ❇️
